jobs:
- job: Windows

  pool:
    vmImage: 'windows-2019'
    
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget

  steps:
  - checkout: self
    clean: true

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.9.1
      checkLatest: false
    
  - task: GitVersion@5
    inputs:
      useConfigFile: true
      configFilePath: gitversion.yml
      updateAssemblyInfo: false

  - powershell: |
        $ErrorActionPreference = 'SilentlyContinue'
        cd $(build.sourcesdirectory)/src/WasmAot.UITests
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.DynamicLinking.UITests
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Node.Sample.Runner
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Threading.UITests
        npm install

    displayName: UI Tests npm dependencies

  - powershell: .\build\build.ps1 -script build\build.cake
    displayName: Build 

  - powershell: |
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Node.Sample.Runner
        .\Validate.ps1

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)
      Contents: ' $(build.sourcesdirectory)\build\nuget\*.nupkg'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-wasm-bootstrap-drop
      ArtifactType: Container

- template: .vsts-ci-linux.yml
  parameters:
    jobName: Linux_netcore2_2
    netcore_version: 2.2.x
    linux_container: nventive/wasm-build:1.3

- template: .vsts-ci-linux.yml
  parameters:
    jobName: Linux_netcore3_0
    netcore_version: 3.0.x
    linux_container: unoplatform/wasm-build:2.0

- template: .vsts-ci-linux.yml
  parameters:
    jobName: Linux_netcore3_1
    netcore_version: 3.1.x
    linux_container: unoplatform/wasm-build:2.0

- job: macOS

  pool:
    vmImage: 'macOS-10.14'

  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)/.nuget
    SourceLinkEnabled: false

  steps:
  - bash: |
      cd $(Agent.WorkFolder)
      wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-mac.zip
      unzip ninja-mac.zip -d ninja-mac
     
    displayName: 'Install Ninja'

  - bash: |
      cd $(Agent.WorkFolder)
      git clone https://github.com/juj/emsdk.git
      cd emsdk
      ./emsdk install latest
      ./emsdk activate latest

    displayName: 'Install Emscripten'

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.7.0
      checkLatest: false

  - bash: |
      export PATH=$PATH:$(Agent.WorkFolder)/ninja-mac
      source $(Agent.WorkFolder)/emsdk/emsdk_env.sh
      msbuild /m /r /t:Publish /p:Configuration=Release src/Uno.Wasm.Bootstrap.sln

    displayName: Build 

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Uno.Wasm.AotTests/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-wasm-bootstrap-macos-aot
      ArtifactType: Container
