parameters:
  jobName: ''

jobs:
- job: ${{ parameters.jobName }}
  timeoutInMinutes: 90

  pool:
    vmImage: 'windows-2019'

  workspace:
    clean: all
      
  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget
    NETCORE_VERSION: ${{ parameters.netcore_version }}

  steps:
  - checkout: self
    clean: true

  - template: build/ci/gitversion.yml
  - template: build/ci/dotnet-install.yml

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      packageType: sdk
      version: 7.0.100-rc.1.22431.12
      includePreviewVersions: true

  - pwsh: |
      cd $(build.sourcesdirectory)/src/Uno.Wasm.Bootstrap
      dotnet msbuild /r /p:Configuration=Release /p:DISABLE_CLIHOST_NET6=true
    displayName: Build bootstrap

  - pwsh: |
      cd $(build.sourcesdirectory)/src/Uno.Wasm.SampleNet5
      $customMonoTempPath="$env:temp\with a space\test"
      mkdir $customMonoTempPath
      dotnet clean -c Release
      dotnet publish /p:Configuration=Release "/p:WasmShellMonoTempFolder=$customMonoTempPath" /p:DISABLE_CLIHOST_NET6=true /p:WasmShellEmccLinkOptimization=false /bl:$(build.artifactstagingdirectory)/SampleNet5-win-temp-with-space.binlog
    displayName: Build Raytracer Sample with Spaces

  - pwsh: |
      cd $(build.sourcesdirectory)/src/Uno.Wasm.Sample.RayTracer
      $customMonoTempPath="$env:temp\with a space\test2"
      mkdir $customMonoTempPath
      dotnet clean -c Release
      dotnet publish -c Release "/p:WasmShellMonoTempFolder=$customMonoTempPath" /p:DISABLE_CLIHOST_NET6=true /p:WasmShellEmccLinkOptimization=false /bl:$(build.artifactstagingdirectory)/aottest-win-temp-with-space.binlog
    displayName: Build Raytracer Sample with Spaces

  - pwsh: |
      cd $(build.sourcesdirectory)/src/Uno.Wasm.Sample.RayTracer
      dotnet clean -c Release
      dotnet publish -c Release /p:DISABLE_CLIHOST_NET6=true /p:WasmShellEmccLinkOptimization=false /bl:$(build.artifactstagingdirectory)/SampleNet5-win.binlog
    displayName: Build Raytracer Sample

  - pwsh: |
      $(build.sourcesdirectory)\build\scripts\run-tests-windows.ps1 `
      "$(build.sourcesdirectory)\src\Uno.Wasm.Sample.RayTracer\bin\Release\net7.0\dist" `
      "$(build.sourcesdirectory)\src\WasmAot.UITests" `
      "http://localhost:8000/"

    displayName: Raytracer UI Tests Net5
    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"

  # Static linking test (net5)
  - pwsh: |
      cd $(build.sourcesdirectory)/src/Uno.Wasm.StaticLinking.Aot.Net5
      dotnet clean -c Release
      dotnet publish -c Release /p:DISABLE_CLIHOST_NET6=true /p:WasmShellEmccLinkOptimization=false /bl:$(build.artifactstagingdirectory)/SampleNet5-win.binlog
    displayName: Build StaticLinking.Aot Sample (net5)

  - pwsh: |
      $(build.sourcesdirectory)\build\scripts\run-tests-windows.ps1 `
      "$(build.sourcesdirectory)\src\Uno.Wasm.StaticLinking.Aot.Net5\bin\Release\net5.0\dist" `
      "$(build.sourcesdirectory)\src\Uno.Wasm.StaticLinking.Aot.UITests" `
      "http://localhost:8000/"

    displayName: StaticLinking.Aot Tests Net5
    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"
      
  # Static linking test (net4)
  - pwsh: |
      cd $(build.sourcesdirectory)/src/Uno.Wasm.StaticLinking.net7
      dotnet clean -c Release
      dotnet publish -c Release /p:DISABLE_CLIHOST_NET6=true /p:WasmShellEmccLinkOptimization=false /bl:$(build.artifactstagingdirectory)/SampleNet7-win.binlog
    displayName: Build StaticLinking.Aot Sample (net7)

  - pwsh: |
      $(build.sourcesdirectory)\build\scripts\run-tests-windows.ps1 `
      "$(build.sourcesdirectory)\src\Uno.Wasm.StaticLinking.Net7\bin\Release\net7.0\dist" `
      "$(build.sourcesdirectory)\src\Uno.Wasm.StaticLinking.Aot.UITests" `
      "http://localhost:8000/"

    displayName: StaticLinking.Aot Tests net7
    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"

  # Thread test
  - pwsh: |
      cd $(build.sourcesdirectory)/src/Uno.Wasm.Threads
      dotnet clean -c Release
      dotnet publish -c Release /p:DISABLE_CLIHOST_NET6=true /p:WasmShellEmccLinkOptimization=false /bl:$(build.artifactstagingdirectory)/sample.threads-win.binlog
    displayName: Build Threading Sample

  - pwsh: |
      $(build.sourcesdirectory)\build\scripts\run-tests-windows.ps1 `
      "$(build.sourcesdirectory)\src\Uno.Wasm.Threads\bin\Release\net6.0\dist" `
      "$(build.sourcesdirectory)\src\Uno.Wasm.Threading.UITests" `
      "http://localhost:8000/"

    displayName: Threading Tests
    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"

  # Thread AOT test
  - pwsh: |
      cd $(build.sourcesdirectory)/src/Uno.Wasm.Threads.Aot
      dotnet clean -c Release
      dotnet publish -c Release /p:DISABLE_CLIHOST_NET6=true /p:WasmShellEmccLinkOptimization=false /bl:$(build.artifactstagingdirectory)/sample.threads-win.binlog
    displayName: Build Threading AOT Sample

  - pwsh: |
      $(build.sourcesdirectory)\build\scripts\run-tests-windows.ps1 `
      "$(build.sourcesdirectory)\src\Uno.Wasm.Threads.Aot\bin\Release\net6.0\dist" `
      "$(build.sourcesdirectory)\src\Uno.Wasm.Threading.UITests" `
      "http://localhost:8000/"

    displayName: Threading AOT Tests
    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-wasm-bootstrap-windows-test
      ArtifactType: Container
