jobs:
- job: Windows

  pool:
    vmImage: 'windows-2019'
    
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget

  steps:
  - checkout: self
    clean: true

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.9.1
      checkLatest: false
    
  - task: GitVersion@5
    inputs:
      useConfigFile: true
      configFilePath: gitversion.yml
      updateAssemblyInfo: false

  - powershell: |
        $ErrorActionPreference = 'SilentlyContinue'
        cd $(build.sourcesdirectory)/src/WasmAot.UITests
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.StaticLinking.Aot.UITests
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Node.Sample.Runner
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Threading.UITests
        npm install

    displayName: UI Tests npm dependencies

  - powershell: .\build\build.ps1 -script build\build.cake
    displayName: Build 

  - powershell: |
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Node.Sample.Runner
        .\Validate.ps1

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)
      Contents: ' $(build.sourcesdirectory)\build\nuget\*.nupkg'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-wasm-bootstrap-drop
      ArtifactType: Container

- template: .vsts-ci-linux.yml
  parameters:
    jobName: Linux_netcore3_1
    netcore_version: 3.1.x
    linux_container: unoplatform/wasm-build:2.3

- template: .vsts-ci-macos.yml
  parameters:
    jobName: macOS_netcore3_1
    vmImage: macOS-10.15
    netcore_version: 3.1.x